AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template GnuPG - Encryption and Decryption Compiler for S3 Data
Globals:
  Function:
    MemorySize: 128
    Timeout: 60
Resources:
  S3FileGPGDecryptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: S3FileGPGDecryption
      Description: Layers App Decrypt File with GPG
      CodeUri: s3://freshers-training/lambda-layer-code/41cd765d485f58254804a70c173ff692
      Handler: main.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::058682646398:role/service-role/gpg-decryption-role-or8p50fh
      Environment:
        Variables:
          DEST_BUCKET: freshers-training
          DEST_PREFIX: gpg/decrypted
          CRYPT_FILE_SUFFIX: .gpg
          PROCESS_ZERO_FILE_SIZE: true
          SEC_KEY_PATH: s3://freshers-training/gpg/private-key/gpg_keys/sec.key
          PASSPHRASE: dcube@2022
      Layers:
      - Ref: GPGBinaryLibLambdaLayer
    Metadata:
      SamResourceId: S3FileGPGDecryptionFunction
  S3FileGPGEncryptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: S3FileGPGEncryption
      Description: Layers App Encrypt File with GPG
      CodeUri: s3://freshers-training/lambda-layer-code/15156b200feaadcb23997db06d4dd7ce
      Handler: main.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::058682646398:role/service-role/gpg-decryption-role-or8p50fh
      Environment:
        Variables:
          DEST_BUCKET: freshers-training
          DEST_PREFIX: gpg/encrypted
          CRYPT_FILE_SUFFIX: .gpg
          PROCESS_ZERO_FILE_SIZE: true
          PUB_KEY_PATH: s3://freshers-training/gpg/private-key/gpg_keys/pub.key
          RECIPIENTS: dcube_latest@dcube.com
      Layers:
      - Ref: GPGBinaryLibLambdaLayer
    Metadata:
      SamResourceId: S3FileGPGEncryptionFunction
  GPGBinaryLibLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GPGBinaryLibraries
      Description: GPG Encryption and Decryption Dependency Libraries Lambda Layer
      ContentUri: s3://freshers-training/lambda-layer-code/f05fce59aa143236e6e6ae762579c867
      CompatibleRuntimes:
      - python3.9
      - python3.8
      - python3.7
      LicenseInfo: null
      RetentionPolicy: Retain
    Metadata:
      SamResourceId: GPGBinaryLibLambdaLayer
Outputs:
  MyLambdaLayerARN:
    Value:
      Ref: GPGBinaryLibLambdaLayer
    Description: GPGBinaryLibLambdaLayer ARN
    Export:
      Name: gpg-binary-lib-lambda-layer-arn
